//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luoghi
    {
        public int Id { get; set; }
        public Nullable<int> CoorX { get; set; }
        public Nullable<int> CoorY { get; set; }
        public string nome { get; set; }
    
        public virtual SensoriLuogo SensoriLuogo { get; set; }
    }
}
