//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensoriLuogo
    {
        public int IdCasa { get; set; }
        public Nullable<int> IdSensore1 { get; set; }
        public Nullable<int> IdSensore2 { get; set; }
        public Nullable<int> IdSensore3 { get; set; }
    
        public virtual Luoghi Luoghi { get; set; }
    }
}
