//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoricoAllarmi
    {
        public int Id { get; set; }
        public Nullable<int> IdSensore { get; set; }
        public Nullable<System.DateTime> OraScatto { get; set; }
        public Nullable<int> ValoreAllarme { get; set; }
        public Nullable<System.DateTime> OraDisatt { get; set; }
        public Nullable<int> IdOperatore { get; set; }
    
        public virtual AnaOperatori AnaOperatori { get; set; }
        public virtual AnaSensori AnaSensori { get; set; }
    }
}
